name: venture
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+1
  firebase_auth: ^0.8.1+3
  google_sign_in: ^4.0.1+1
  cupertino_icons: ^0.1.2
  progress_indicators: ^0.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  
  font_awesome_flutter: ^8.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/full-bloom.png
    - assets/images/mountains.jpeg
    - assets/images/mountains.jpg

fonts:
      - family: icomoon
        fonts:
        - asset: assets/fonts/IcoMoon.ttf

