name: venture
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^3.2.4
  firebase_auth: ^0.6.6
  cupertino_icons: ^0.1.2
  progress_indicators: ^0.1.2
  flutter_swiper: ^1.1.4
  audioplayers: ^0.9.0
  http: ^0.12.0
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  
  font_awesome_flutter: ^8.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/full-bloom.png
    - assets/images/mountains.jpeg
    - assets/images/mountains.jpg
    - assets/audio/self_confidence.mp3
    - assets/audio/in_plane.mp3
    - assets/audio/relaxing_music.mp3
    - assets/audio/relaxing_music_2.mp3

fonts:
      - family: icomoon
        fonts:
        - asset: assets/fonts/IcoMoon.ttf

